# Generated by Django 5.1.1 on 2025-01-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reports', '0002_remove_report_status_report_is_active_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='ChartType',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
    ]
