# Generated by Django 5.1.1 on 2025-01-16 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_ar_name_user_created_at_user_created_by_and_more'),
        ('roles', '0002_permission_roles_permi_key_2a3aa1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
