# Generated by Django 5.1.1 on 2025-02-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_connection_name_connection_connection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connection',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='schema',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='connection',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
