# Generated by Django 5.1.1 on 2025-01-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_status_report_is_active_chart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='query',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='connection_type',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.charttype'),
        ),
        migrations.AddField(
            model_name='chart',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
        ),
        migrations.CreateModel(
            name='ChartAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=80)),
                ('axis', models.CharField(choices=[('x', 'x'), ('y', 'y'), ('z', 'z')], max_length=10)),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.chart')),
            ],
        ),
    ]
