# Generated by Django 5.1.1 on 2025-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_chart_type_remove_report_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaxis',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='charttype',
            name='ar_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
