# Generated by Django 5.1.1 on 2025-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_chartaxis_name_alter_charttype_ar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttype',
            name='color',
            field=models.CharField(default='#000', max_length=10),
        ),
    ]
