# Generated by Django 5.1.1 on 2025-02-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_connection_connection_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='width',
            field=models.CharField(choices=[('50%', '1/2'), ('100%', 'full')], default='50%', max_length=10),
        ),
        migrations.AlterField(
            model_name='chartaxis',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='axes', to='reports.chart'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.IntegerField(),
        ),
    ]
