# Generated by Django 5.1.1 on 2025-01-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_charttype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charttype',
            name='color',
        ),
        migrations.AddField(
            model_name='chartaxis',
            name='color',
            field=models.CharField(default='#000', max_length=10),
        ),
    ]
