# Generated by Django 5.1.1 on 2025-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_charttype_color_chartaxis_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaxis',
            name='axis',
            field=models.CharField(choices=[('x', 'x'), ('y', 'y')], max_length=10),
        ),
    ]
