# Generated by Django 5.1.1 on 2025-01-16 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['key'], name='roles_permi_key_2a3aa1_idx'),
        ),
    ]
